export enum RoutePath {
    home = "home",
    account = "account",
    auth = "auth",
    login = "login",
    webhooks = "webhooks",
    users = "users",
    workspaceSettings = "workspace-settings",
    workspaceMembers = "workspace-members",
    phoneConfigs = "phone-configs",
    phoneConfigNew = "phone-configs/new",
    phoneConfigDetail = "phone-configs/:id",
    register = "register",
    verifyEmail = "verify-email",
    forgotPassword = "forgot-password",
    resetPassword = "reset-password",
    acceptInvitation = "accept-invitation",
    invitation = "invitation",
    verifyEmailRequired = "verify-email-required",
    privacyPolicy = "privacy-policy",
    termsOfService = "terms-of-service",
    billing = "billing",
    billingAdmin = "billing-admin",
    billingSuccess = "billing-success",
    billingCancel = "billing-cancel",
    devtools = "devtools",
}
