export enum ServerEndpoints {
    user = "user",
    message = "message",
    contact = "contact",
    messaging_product = "messaging-product",
    messaging_product_contact = "messaging-product-contact",
    webhook = "webhook",
    log = "log",
    campaign = "campaign",
    status = "status",
    error = "error",

    step_machine = "step-machine",
    flow = "flow",
    step = "step",

    whatsapp_template = "whatsapp-template",
    websocket = "websocket",
    media = "media",
    whatsapp = "whatsapp",
    new = "new",
    conversation = "conversation",
    oauth = "oauth",
    token = "token",
    me = "me",
    resetPassword = "reset-password",
    content = "content",
    like = "like",
    count = "count",
    block = "block",

    workspace = "workspace",
    member = "member",
    invitation = "invitation",
    phone_config = "phone-config",
    register = "register",
    request_code = "request-code",
    verify_code = "verify-code",
    pin_authenticate = "pin-authenticate",
    deregister = "deregister",
    verify_email = "verify-email",
    forgot_password = "forgot-password",
    accept_invitation = "accept-invitation",
    resend_verification = "resend-verification",
    auth = "auth",
    test = "test",

    billing = "billing",
    billing_plan = "plan",
    billing_subscription = "subscription",
    billing_usage = "usage",
    billing_endpoint_weight = "endpoint-weight",
    billing_checkout = "checkout",
    billing_manual = "manual",
    billing_reactivate = "reactivate",
}
