export enum ServerEndpoints {
    user = "user",
    message = "message",
    contact = "contact",
    messaging_product = "messaging-product",
    messaging_product_contact = "messaging-product-contact",
    webhook = "webhook",
    log = "log",
    campaign = "campaign",
    status = "status",
    error = "error",

    step_machine = "step-machine",
    flow = "flow",
    step = "step",

    whatsapp_template = "whatsapp-template",
    websocket = "websocket",
    media = "media",
    whatsapp = "whatsapp",
    new = "new",
    conversation = "conversation",
    oauth = "oauth",
    token = "token",
    me = "me",
    resetPassword = "reset-password",
    content = "content",
    like = "like",
    count = "count",
    block = "block",

    workspace = "workspace",
    member = "member",
    invitation = "invitation",
    phone_config = "phone-config",
    register = "register",
    verify_email = "verify-email",
    forgot_password = "forgot-password",
    accept_invitation = "accept-invitation",
    resend_verification = "resend-verification",
    auth = "auth",
}
